[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/square/go-jose"
  version = "2.1.6"

[[constraint]]
  name = "github.com/patrickmn/go-cache"
  version = "2.1.0"
